# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anapencere_python.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 50, 501, 351))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 47, 13))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(144, 280, 111, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(140, 30, 111, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 60, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(140, 100, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(140, 150, 111, 71))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu_r_n_Listele = QtWidgets.QMenu(self.menubar)
        self.menu_r_n_Listele.setObjectName("menu_r_n_Listele")
        MainWindow.setMenuBar(self.menubar)
        self.action_r_n_Kategori_Ekle = QtWidgets.QAction(MainWindow)
        self.action_r_n_Kategori_Ekle.setObjectName("action_r_n_Kategori_Ekle")
        self.action_r_n_Kategori_Ekle_2 = QtWidgets.QAction(MainWindow)
        self.action_r_n_Kategori_Ekle_2.setObjectName("action_r_n_Kategori_Ekle_2")
        self.action_r_n_Listele = QtWidgets.QAction(MainWindow)
        self.action_r_n_Listele.setObjectName("action_r_n_Listele")
        self.menu_r_n_Listele.addAction(self.action_r_n_Kategori_Ekle_2)
        self.menu_r_n_Listele.addAction(self.action_r_n_Listele)
        self.menubar.addAction(self.menu_r_n_Listele.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Ürünler"))
        self.label.setText(_translate("MainWindow", "Ürün Adı"))
        self.label_2.setText(_translate("MainWindow", "Miktar"))
        self.label_3.setText(_translate("MainWindow", "Kategori"))
        self.label_4.setText(_translate("MainWindow", "Açıklama"))
        self.pushButton.setText(_translate("MainWindow", "Ekle"))
        self.menu_r_n_Listele.setTitle(_translate("MainWindow", "Ürünler"))
        self.action_r_n_Kategori_Ekle.setText(_translate("MainWindow", "Ürün Kategori Ekle"))
        self.action_r_n_Kategori_Ekle_2.setText(_translate("MainWindow", "Ürün Kategori Ekle"))
        self.action_r_n_Listele.setText(_translate("MainWindow", "Ürün Listele"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
