# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_python.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label_kullaniciadi = QtWidgets.QLabel(Form)
        self.label_kullaniciadi.setGeometry(QtCore.QRect(40, 30, 61, 16))
        self.label_kullaniciadi.setObjectName("label_kullaniciadi")
        self.label_password = QtWidgets.QLabel(Form)
        self.label_password.setGeometry(QtCore.QRect(40, 90, 47, 13))
        self.label_password.setObjectName("label_password")
        self.lineEdit_kullaniciAdi = QtWidgets.QLineEdit(Form)
        self.lineEdit_kullaniciAdi.setGeometry(QtCore.QRect(120, 30, 113, 20))
        self.lineEdit_kullaniciAdi.setObjectName("lineEdit_kullaniciAdi")
        self.lineEdit_password = QtWidgets.QLineEdit(Form)
        self.lineEdit_password.setGeometry(QtCore.QRect(120, 80, 113, 20))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_giris = QtWidgets.QPushButton(Form)
        self.pushButton_giris.setGeometry(QtCore.QRect(160, 130, 75, 23))
        self.pushButton_giris.setObjectName("pushButton_giris")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_kullaniciadi.setText(_translate("Form", "Kullanıcı Adı"))
        self.label_password.setText(_translate("Form", "Şifre"))
        self.pushButton_giris.setText(_translate("Form", "Giriş Yap"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
